[[constraint]]
  name = "github.com/alexcesaro/statsd"
  version = "2.0.0"

[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "0.11.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/topfreegames/go-gcm"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/pg.v5"
  version = "5.3.3"
